#! /bin/bash

# base code stolen from:
# http://scripting.tribe.net/thread/68d349f4-9824-4338-8a19-95fb085ec026

# Copyright (c) 2011 Spike Grobstein <spikegrobstein@mac.com>
# 
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
# 
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
# 
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
# THE SOFTWARE.

int_to_ip () 
{ 
  echo -n $(($(($(($((${1}/256))/256))/256))%256)). 
  echo -n $(($(($((${1}/256))/256))%256)). 
  echo -n $(($((${1}/256))%256)). 
  echo $((${1}%256)) 
} 

# check commandline for right number of arguments and print usage if necessary.
if [[ $# != 1 ]]; then
  echo "USAGE:"
  echo "    $0 <ip_address_int>"
  echo ""
  echo "    Convert an IPv4 address (as a 32-bit integer) to the dotted octet notation"
  echo "    eg:"
  echo "        $0 176941832 #=> 10.139.235.8"
  echo ""
  
  exit 0
fi

int_to_ip $1
