#! /bin/bash

# base code stolen from:
# http://scripting.tribe.net/thread/68d349f4-9824-4338-8a19-95fb085ec026

ip_to_int () 
{ 
  IP=$1; IPNUM=0 
  for (( i=0 ; i<4 ; ++i )); do 
    ((IPNUM+=${IP%%.*}*$((256**$((3-${i})))))) 
    IP=${IP#*.} 
  done 
  echo $IPNUM 
} 

# check commandline for right number of arguments and print usage if necessary.
if [[ $# != 1 ]]; then
  echo "USAGE:"
  echo "    $0 <ip_address>"
  echo ""
  echo "    Convert an IPv4 address in dotted octet notation to a 32-bit integer."
  echo "    eg:"
  echo "        $0 10.139.235.8 #=> 176941832"
  echo ""
  
  exit 0
fi


ip_to_int $1
